name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12, 3.11]

    # 👇 Add test-friendly env so no HTTPS redirect & predictable settings
    env:
      DJANGO_SETTINGS_MODULE: wolvcapital.settings
      DEBUG: "1" # disable prod security in tests
      SECRET_KEY: "ci-test-key" # any non-empty value is fine for tests
      PYTHONWARNINGS: default

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt','**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      # Optional: avoid staticfiles warning
      - name: Prepare staticfiles dir
        run: mkdir -p staticfiles

      - name: Lint (Ruff)
        run: |
          if python -c "import importlib,sys; sys.exit(0 if importlib.util.find_spec('ruff') else 1)"; then
            python -m ruff check . || true
          else
            echo "ruff not installed; skipping lint"
          fi

      - name: Type check (mypy)
        run: |
          if python -c "import importlib,sys; sys.exit(0 if importlib.util.find_spec('mypy') else 1)"; then
            python -m mypy || true
          else
            echo "mypy not installed; skipping type check"
          fi

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: Static reference check
        run: |
          python tools/check_static_references.py

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: Check static references
        run: |
          python tools/check_static_references.py

      - name: Django system check
        run: python manage.py check
      - name: Upload staticfiles artifact
        uses: actions/upload-artifact@v4
        with:
          name: staticfiles-${{ matrix.python-version }}
          path: staticfiles/

      - name: Run tests and capture output
        run: |
          set -o pipefail
          python -u manage.py test -v 2 2>&1 | tee test-output.txt

      - name: Upload test output
        uses: actions/upload-artifact@v4
        with:
          name: test-output-${{ matrix.python-version }}
          path: test-output.txt
      - name: Upload staticfiles
        uses: actions/upload-artifact@v4
        with:
          name: staticfiles-${{ matrix.python-version }}
          path: staticfiles
